# fly.toml app configuration file generated for f1-explorer-app
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "f1-explorer-app"
primary_region = "iad"

[build]
  builder = "paketobuildpacks"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 3002
  processes = ["app"]

  [services.http_checks]
    enabled = true
    uri = "/api/health"

[[services]]
  internal_port = 3000
  processes = ["app"]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
